version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - backbone

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
    networks:
      - backbone
  mongodata:
    image: tianon/true
    volumes:
      - /data/db:/data/db
networks:
  backbone:
